// cargo-fuzz target for the `__MODULE__` module of `__CRATE__`.
// Generated by porting-kit/harnesses/fuzz/gen_fuzz_target.sh — edit the body to
// call your module's real entry point.
//
// The contract this enforces: the ported code must NEVER panic, abort, or exhibit
// UB on arbitrary bytes. That is the memory-safety guarantee the C original
// couldn't make. A crash here is a release blocker (PLAYBOOK Phase 4, gate 3).
#![no_main]

use libfuzzer_sys::fuzz_target;

// If your input is structured, prefer `arbitrary`:
//   use arbitrary::Arbitrary;
//   #[derive(Arbitrary, Debug)]
//   struct Input { /* typed fields */ }

fuzz_target!(|data: &[u8]| {
    // Feed raw bytes to the module's public parse/decode surface. Replace this
    // with the real call. The parser must return a Result/Option and never
    // panic — no unwrap()/expect()/indexing that can go out of bounds on
    // hostile input.
    //
    // Feed it the bytes the PRODUCTION READER sees, decoded the way that
    // reader decodes them — never `if let Ok(text) = from_utf8(data)`, which
    // silently skips every input that is not UTF-8 and so fuzzes a parser the
    // reader may never reach. In lsof-rs the reader was `read_to_string`: one
    // such byte failed the read, the whole table was dropped, and any process
    // could hide from the tool (LESSONS #067). If the reader decodes lossily,
    // do the same here; if it rejects, the rejection is behaviour to assert,
    // not input to skip.
    let text = String::from_utf8_lossy(data);
    let _ = __CRATE__::__MODULE__::parse(&text);

    // If the parser has a round-trip invariant, assert it (parse->render->parse):
    //   if let Ok(v) = __CRATE__::__MODULE__::parse(&text) {
    //       let rendered = __CRATE__::__MODULE__::render(&v);
    //       assert_eq!(Ok(v), __CRATE__::__MODULE__::parse(&rendered));
    //   }
});
